from flask.ext.wtf import Form
from wtforms import TextField, TextAreaField, SubmitField, PasswordField, validators, ValidationError, SelectField


class S3ImportForm(Form):
    deviceId = TextField(u'Device ID', validators=[validators.required()])
    notificationEmail = TextField("Notification Email",  [validators.email("Please enter 7 characters to search")])
    region = SelectField(u'Region', choices=[('us-east-1', 'us-east-1'), ('us-west-1', 'us-west-1'),
                    ('us-west-2', 'us-west-2'), ('eu-west-1 ', 'eu-west-1'), ('ap-southeast-1', 'ap-southeast-1')])
    acl = TextField("ACL",  [validators.email("Please enter an ACL if you like")])
    bucket = TextField("Import Bucket", [validators.required("Please enter the bucket name for importing files")])
    logPrefix = TextField("Log Prefix", [validators.required("Please enter a log prefix")])
    prefix = TextField("Prefix", [validators.required("Please enter a prefix")])
    substitutions = TextField("Replace box1 with box2")
    substitutionsb = TextField("Ignore directories")
    substitutions2 = TextField("Replace box1 with box2")
    substitutions2b = TextField("Ignore directories")
    logBucket = TextField("Log Bucket", [validators.required("Please enter the bucket name for job logs")])
    trueCryptPassword = TextField("TrueCrypt Password")
    pinCode = TextField("Pin Code")
    cacheControl = TextField("Cache Control")
    contentDisposition = TextField("Content Disposition")
    contentLanguage = TextField("Content Language")
    contentTypes = SelectField(u'Map Content types', choices=[('', ''), ('yes', 'yes')])
    diskTimestampMetadataKey = TextField("Disk Time Stamp Metadata Key")
    expires = TextField("Expires")
    ignore = SelectField(u'Exclude Lost+Found', choices=[('', ''), ('yes', 'yes')])
    ignore2 = SelectField(u'Exclude Recycle Bin', choices=[('', ''), ('yes', 'yes')])
    ignore3 = SelectField(u'Exclude ~ and .swp files', choices=[('', ''), ('yes', 'yes')])
    ignore4 = TextField("Ignore directories")
    ignore5 = TextField("Ignore directories")
    ignore6 = TextField("Ignore files with specific extension")
    ignore7 = TextField("Ignore files with specific extension")
    setContentEncodingForGzFiles = SelectField(u'Set Encoding for .gz files', choices=[('', ''), ('yes', 'Yes')])
    staticMetadata = TextField("Static Metadata")
    storageClass = SelectField(u'Select Storage Class', choices=[('', ''), ('REDUCED_REDUNDANCY', 'REDUCED_REDUNDANCY')])
    serviceLevel = SelectField(u'Expedite return shipping', choices=[('', ''), ('expeditedShipping', 'Expedited Shipping'), ('standard', 'standard Shipping')])
    name = TextField("Name",  [validators.required("Please enter your name, it's required")])
    company = TextField("Company")
    street1 = TextField("Street1",  [validators.required("Please enter your street, it's required")])
    street2 = TextField("Street2")
    street3 = TextField("Street3")
    city = TextField("City",  [validators.required("Please enter your city, it's required")])
    stateOrProvince = TextField("State or Province",  [validators.required("Please enter your state or province, it's required")])
    postalCode = TextField("Postal Code",  [validators.required("Please enter your postal code, it's required")])
    phoneNumber = TextField("Phone Number",  [validators.required("Please enter your phone number, it's required")])
    country = TextField("Country",  [validators.required("Please enter your country, it's required")])
    dataDescription = TextField("Description of The Data",  [validators.required("Please enter a description, it's required")])
    encryptedData = SelectField(u'Encrypted Data', choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')])
    exportCertifierName = TextField("Shipper Name",  [validators.required("Please enter a name, it's required")])
    requiresExportLicense = SelectField(u'Requires Export License', choices=[('', ''), ('Yes', 'Yes'), ('No', 'No')])
    deviceValue = TextField("Device Value",  [validators.required("Please enter a value, it's required")])
    deviceCountryOfOrigin = TextField("Drive Manufacture Country",  [validators.required("Please a country, it's required")])
    deviceType = SelectField(u'Device Type', choices=[('', ''), ('externalStorageDevice', 'externalStorageDevice'), ('usbFlashDrive', 'usbFlashDrive'), ('sataDrive', 'sataDrive')])
    typeOfExport = SelectField(u'Type of Export', choices=[('', ''), ('return', 'return'), ('permanent', 'permanent'), ('temporary', 'temporary')])
    archivecomment = TextField("Archive Comment")
    submit = SubmitField("Generate")

